//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensayo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peliculas
    {
        public Peliculas()
        {
            this.Carteleras = new HashSet<Carteleras>();
            this.Reservas = new HashSet<Reservas>();
        }
    
        public int IdPelicula { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Imagen { get; set; }
        public int IdCalificacion { get; set; }
        public int IdGenero { get; set; }
        public int Duracion { get; set; }
        public System.DateTime FechaCarga { get; set; }
    
        public virtual Calificaciones Calificaciones { get; set; }
        public virtual ICollection<Carteleras> Carteleras { get; set; }
        public virtual Generos Generos { get; set; }
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
