//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensayo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sedes
    {
        public Sedes()
        {
            this.Carteleras = new HashSet<Carteleras>();
            this.Reservas = new HashSet<Reservas>();
        }
    
        public int IdSede { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public decimal PrecioGeneral { get; set; }
    
        public virtual ICollection<Carteleras> Carteleras { get; set; }
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
