//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensayo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposDocumentos
    {
        public TiposDocumentos()
        {
            this.Reservas = new HashSet<Reservas>();
        }
    
        public int IdTipoDocumento { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
